<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kashish Mukheja">
<meta name="dcterms.date" content="2023-01-01">

<title>kashish18.github.io - EDA and Train Various Classic ML Models (PGP Project)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">kashish18.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kashish18" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kashmkj18" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">EDA and Train Various Classic ML Models (PGP Project)</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">jupyter</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Kashish Mukheja </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 1, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="mission-statement" class="level2">
<h2 class="anchored" data-anchor-id="mission-statement">Mission Statement</h2>
<p>To perform multi-variate analysis, EDA on the signal’s dataset. Also, experiment on various ML Models including Logistic Regression, RandomForest, KNN, etc to compare the pros and cons of each of those and provide insights.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-tags="[]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip3 install seaborn</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip3 install imblearn</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip3 install statsmodels</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip3 install xgboost</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Collecting seaborn
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 5.5 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: matplotlib!=3.6.1,&gt;=3.1 in /root/mambaforge/lib/python3.9/site-packages (from seaborn) (3.5.2)
Requirement already satisfied: numpy!=1.24.0,&gt;=1.17 in /root/mambaforge/lib/python3.9/site-packages (from seaborn) (1.23.0)
Requirement already satisfied: pandas&gt;=0.25 in /root/mambaforge/lib/python3.9/site-packages (from seaborn) (1.4.3)
Requirement already satisfied: packaging&gt;=20.0 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (21.3)
Requirement already satisfied: cycler&gt;=0.10 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (0.11.0)
Requirement already satisfied: fonttools&gt;=4.22.0 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (4.33.3)
Requirement already satisfied: python-dateutil&gt;=2.7 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (2.8.2)
Requirement already satisfied: pillow&gt;=6.2.0 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (9.1.1)
Requirement already satisfied: kiwisolver&gt;=1.0.1 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (1.4.3)
Requirement already satisfied: pyparsing&gt;=2.2.1 in /root/mambaforge/lib/python3.9/site-packages (from matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (3.0.9)
Requirement already satisfied: pytz&gt;=2020.1 in /root/mambaforge/lib/python3.9/site-packages (from pandas&gt;=0.25-&gt;seaborn) (2022.1)
Requirement already satisfied: six&gt;=1.5 in /root/mambaforge/lib/python3.9/site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib!=3.6.1,&gt;=3.1-&gt;seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.10.1-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.0/226.0 kB 11.2 MB/s eta 0:00:00
Requirement already satisfied: scipy&gt;=1.3.2 in /root/mambaforge/lib/python3.9/site-packages (from imbalanced-learn-&gt;imblearn) (1.8.1)
Requirement already satisfied: scikit-learn&gt;=1.0.2 in /root/mambaforge/lib/python3.9/site-packages (from imbalanced-learn-&gt;imblearn) (1.1.1)
Requirement already satisfied: threadpoolctl&gt;=2.0.0 in /root/mambaforge/lib/python3.9/site-packages (from imbalanced-learn-&gt;imblearn) (3.1.0)
Collecting joblib&gt;=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 38.3 MB/s eta 0:00:00
Requirement already satisfied: numpy&gt;=1.17.3 in /root/mambaforge/lib/python3.9/site-packages (from imbalanced-learn-&gt;imblearn) (1.23.0)
Installing collected packages: joblib, imbalanced-learn, imblearn
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
Successfully installed imbalanced-learn-0.10.1 imblearn-0.0 joblib-1.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting statsmodels
  Downloading statsmodels-0.13.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 39.1 MB/s eta 0:00:0000:01:00:01
Requirement already satisfied: scipy&gt;=1.3 in /root/mambaforge/lib/python3.9/site-packages (from statsmodels) (1.8.1)
Requirement already satisfied: packaging&gt;=21.3 in /root/mambaforge/lib/python3.9/site-packages (from statsmodels) (21.3)
Requirement already satisfied: pandas&gt;=0.25 in /root/mambaforge/lib/python3.9/site-packages (from statsmodels) (1.4.3)
Requirement already satisfied: numpy&gt;=1.17 in /root/mambaforge/lib/python3.9/site-packages (from statsmodels) (1.23.0)
Collecting patsy&gt;=0.5.2
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 28.7 MB/s eta 0:00:00
Requirement already satisfied: pyparsing!=3.0.5,&gt;=2.0.2 in /root/mambaforge/lib/python3.9/site-packages (from packaging&gt;=21.3-&gt;statsmodels) (3.0.9)
Requirement already satisfied: pytz&gt;=2020.1 in /root/mambaforge/lib/python3.9/site-packages (from pandas&gt;=0.25-&gt;statsmodels) (2022.1)
Requirement already satisfied: python-dateutil&gt;=2.8.1 in /root/mambaforge/lib/python3.9/site-packages (from pandas&gt;=0.25-&gt;statsmodels) (2.8.2)
Requirement already satisfied: six in /root/mambaforge/lib/python3.9/site-packages (from patsy&gt;=0.5.2-&gt;statsmodels) (1.16.0)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-0.5.3 statsmodels-0.13.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting xgboost
  Downloading xgboost-1.7.4-py3-none-manylinux2014_x86_64.whl (193.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 MB 4.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy in /root/mambaforge/lib/python3.9/site-packages (from xgboost) (1.23.0)
Requirement already satisfied: scipy in /root/mambaforge/lib/python3.9/site-packages (from xgboost) (1.8.1)
Installing collected packages: xgboost
Successfully installed xgboost-1.7.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv</code></pre>
</div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing libraries</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> time <span class="im">import</span> time</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> randint <span class="im">as</span> sp_randint</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn <span class="im">import</span> metrics</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> RandomizedSearchCV</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q1.-import-and-understand-the-data" class="level1">
<h1>Q1. Import and understand the data</h1>
<section id="a.-import-signal-data.csv-as-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="a.-import-signal-data.csv-as-dataframe">A. Import ‘signal-data.csv’ as DataFrame</h2>
<div class="cell" data-execution_count="84">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_signal <span class="op">=</span> pd.read_csv(<span class="st">'signal-data.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="85">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_signal.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="85">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">581</th>
<th data-quarto-table-cell-role="th">582</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">584</th>
<th data-quarto-table-cell-role="th">585</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">588</th>
<th data-quarto-table-cell-role="th">589</th>
<th data-quarto-table-cell-role="th">Pass/Fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2008-07-19 11:55:00</td>
<td>3030.93</td>
<td>2564.00</td>
<td>2187.7333</td>
<td>1411.1265</td>
<td>1.3602</td>
<td>100.0</td>
<td>97.6133</td>
<td>0.1242</td>
<td>1.5005</td>
<td>...</td>
<td>NaN</td>
<td>0.5005</td>
<td>0.0118</td>
<td>0.0035</td>
<td>2.3630</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>-1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2008-07-19 12:32:00</td>
<td>3095.78</td>
<td>2465.14</td>
<td>2230.4222</td>
<td>1463.6606</td>
<td>0.8294</td>
<td>100.0</td>
<td>102.3433</td>
<td>0.1247</td>
<td>1.4966</td>
<td>...</td>
<td>208.2045</td>
<td>0.5019</td>
<td>0.0223</td>
<td>0.0055</td>
<td>4.4447</td>
<td>0.0096</td>
<td>0.0201</td>
<td>0.0060</td>
<td>208.2045</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2008-07-19 13:17:00</td>
<td>2932.61</td>
<td>2559.94</td>
<td>2186.4111</td>
<td>1698.0172</td>
<td>1.5102</td>
<td>100.0</td>
<td>95.4878</td>
<td>0.1241</td>
<td>1.4436</td>
<td>...</td>
<td>82.8602</td>
<td>0.4958</td>
<td>0.0157</td>
<td>0.0039</td>
<td>3.1745</td>
<td>0.0584</td>
<td>0.0484</td>
<td>0.0148</td>
<td>82.8602</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2008-07-19 14:43:00</td>
<td>2988.72</td>
<td>2479.90</td>
<td>2199.0333</td>
<td>909.7926</td>
<td>1.3204</td>
<td>100.0</td>
<td>104.2367</td>
<td>0.1217</td>
<td>1.4882</td>
<td>...</td>
<td>73.8432</td>
<td>0.4990</td>
<td>0.0103</td>
<td>0.0025</td>
<td>2.0544</td>
<td>0.0202</td>
<td>0.0149</td>
<td>0.0044</td>
<td>73.8432</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2008-07-19 15:22:00</td>
<td>3032.24</td>
<td>2502.87</td>
<td>2233.3667</td>
<td>1326.5200</td>
<td>1.5334</td>
<td>100.0</td>
<td>100.3967</td>
<td>0.1235</td>
<td>1.5031</td>
<td>...</td>
<td>NaN</td>
<td>0.4800</td>
<td>0.4766</td>
<td>0.1045</td>
<td>99.3032</td>
<td>0.0202</td>
<td>0.0149</td>
<td>0.0044</td>
<td>73.8432</td>
<td>-1</td>
</tr>
</tbody>
</table>

<p>5 rows × 592 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="86">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_signal.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="86">
<pre><code>(1567, 592)</code></pre>
</div>
</div>
</section>
<section id="b.-print-5-point-summary-and-share-at-least-2-observations" class="level2">
<h2 class="anchored" data-anchor-id="b.-print-5-point-summary-and-share-at-least-2-observations">B. Print 5 point summary and share at least 2 observations</h2>
<div class="cell" data-execution_count="87">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># df_signal.describe() Gives the statistical summary.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>df_signal.describe().loc[[<span class="st">'min'</span>,<span class="st">'25%'</span>,<span class="st">'50%'</span>,<span class="st">'75%'</span>,<span class="st">'max'</span>]] <span class="co"># Prints the 5 point summary</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="87">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">581</th>
<th data-quarto-table-cell-role="th">582</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">584</th>
<th data-quarto-table-cell-role="th">585</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">588</th>
<th data-quarto-table-cell-role="th">589</th>
<th data-quarto-table-cell-role="th">Pass/Fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>2743.24</td>
<td>2158.7500</td>
<td>2060.6600</td>
<td>0.0000</td>
<td>0.6815</td>
<td>100.0</td>
<td>82.1311</td>
<td>0.0000</td>
<td>1.1910</td>
<td>-0.0534</td>
<td>...</td>
<td>0.00000</td>
<td>0.477800</td>
<td>0.0060</td>
<td>0.0017</td>
<td>1.197500</td>
<td>-0.016900</td>
<td>0.0032</td>
<td>0.0010</td>
<td>0.0000</td>
<td>-1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>2966.26</td>
<td>2452.2475</td>
<td>2181.0444</td>
<td>1081.8758</td>
<td>1.0177</td>
<td>100.0</td>
<td>97.9200</td>
<td>0.1211</td>
<td>1.4112</td>
<td>-0.0108</td>
<td>...</td>
<td>46.18490</td>
<td>0.497900</td>
<td>0.0116</td>
<td>0.0031</td>
<td>2.306500</td>
<td>0.013425</td>
<td>0.0106</td>
<td>0.0033</td>
<td>44.3686</td>
<td>-1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>3011.49</td>
<td>2499.4050</td>
<td>2201.0667</td>
<td>1285.2144</td>
<td>1.3168</td>
<td>100.0</td>
<td>101.5122</td>
<td>0.1224</td>
<td>1.4616</td>
<td>-0.0013</td>
<td>...</td>
<td>72.28890</td>
<td>0.500200</td>
<td>0.0138</td>
<td>0.0036</td>
<td>2.757650</td>
<td>0.020500</td>
<td>0.0148</td>
<td>0.0046</td>
<td>71.9005</td>
<td>-1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>3056.65</td>
<td>2538.8225</td>
<td>2218.0555</td>
<td>1591.2235</td>
<td>1.5257</td>
<td>100.0</td>
<td>104.5867</td>
<td>0.1238</td>
<td>1.5169</td>
<td>0.0084</td>
<td>...</td>
<td>116.53915</td>
<td>0.502375</td>
<td>0.0165</td>
<td>0.0041</td>
<td>3.295175</td>
<td>0.027600</td>
<td>0.0203</td>
<td>0.0064</td>
<td>114.7497</td>
<td>-1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>3356.35</td>
<td>2846.4400</td>
<td>2315.2667</td>
<td>3715.0417</td>
<td>1114.5366</td>
<td>100.0</td>
<td>129.2522</td>
<td>0.1286</td>
<td>1.6564</td>
<td>0.0749</td>
<td>...</td>
<td>737.30480</td>
<td>0.509800</td>
<td>0.4766</td>
<td>0.1045</td>
<td>99.303200</td>
<td>0.102800</td>
<td>0.0799</td>
<td>0.0286</td>
<td>737.3048</td>
<td>1.0</td>
</tr>
</tbody>
</table>

<p>5 rows × 591 columns</p>
</div>
</div>
</div>
<section id="observations" class="level3">
<h3 class="anchored" data-anchor-id="observations">Observations</h3>
<ol type="1">
<li>There are certain features which have minimum values as 0, while the maximum value go as high as 3000s and above. All these features are floating point numbers.</li>
<li>The target feature “Pass/Fail”, has values for min, 25%, 50%, &amp; 75% equals “-1”. This indicates that at-least till Q3, target features have value as “-1”. Less than or equal to last 25%ile of the values are “1”. Hence, possible majority of the target feature has yield status as “Pass”.</li>
<li>Feature/Column “5” above, has all the values as 100.</li>
</ol>
</section>
</section>
</section>
<section id="q2.-data-cleansing" class="level1">
<h1>Q2. Data cleansing</h1>
<section id="a.-write-a-for-loop-which-will-remove-all-the-features-with-20-null-values-and-impute-rest-with-mean-of-the-feature" class="level2">
<h2 class="anchored" data-anchor-id="a.-write-a-for-loop-which-will-remove-all-the-features-with-20-null-values-and-impute-rest-with-mean-of-the-feature">A. Write a for loop which will remove all the features with 20%+ Null values and impute rest with mean of the feature</h2>
<div class="cell" data-execution_count="88">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df_signal.isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="88">
<pre><code>Time          0
0             6
1             7
2            14
3            14
             ..
586           1
587           1
588           1
589           1
Pass/Fail     0
Length: 592, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="89">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df_signal.iloc[:,<span class="dv">1</span>:<span class="op">-</span><span class="dv">1</span>].columns:</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> df_signal[col].isnull().<span class="bu">sum</span>()<span class="op">*</span><span class="dv">100</span><span class="op">/</span><span class="bu">len</span>(df_signal[col]) <span class="op">&lt;</span> <span class="dv">20</span>:</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        df_signal[col].fillna(df_signal[col].mean(), inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        df_signal.drop(col, axis<span class="op">=</span><span class="dv">1</span>,inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="90">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df_signal.isnull().<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="90">
<pre><code>Time         0
398          0
392          0
393          0
394          0
            ..
188          0
187          0
186          0
185          0
Pass/Fail    0
Length: 560, dtype: int64</code></pre>
</div>
</div>
<ul>
<li>Hence, 32 columns have been dropped, because they had more than 20% of the data as null values.</li>
<li>Remaining columns, the mean values have been imputed with mean.</li>
</ul>
</section>
<section id="b.-identify-and-drop-the-features-which-are-having-same-value-for-all-the-rows" class="level2">
<h2 class="anchored" data-anchor-id="b.-identify-and-drop-the-features-which-are-having-same-value-for-all-the-rows">B. Identify and drop the features which are having same value for all the rows</h2>
<div class="cell" data-execution_count="91">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For feature to have same value for all rows. There are several ways to fetch those.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The easiest way is to check if the feature's min and max value is same, that means all the </span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># values in that feature are same.</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df_signal.columns:</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> df_signal[col].<span class="bu">min</span>()<span class="op">==</span>df_signal[col].<span class="bu">max</span>():</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        df_signal.drop(col, axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="92">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_signal.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="92">
<pre><code>(1567, 444)</code></pre>
</div>
</div>
<ul>
<li>Hence, 116 columns have been removed as they had same values for all the rows</li>
</ul>
</section>
<section id="c.-drop-other-features-if-required-using-relevant-functional-knowledge.-clearly-justify-the-same" class="level2">
<h2 class="anchored" data-anchor-id="c.-drop-other-features-if-required-using-relevant-functional-knowledge.-clearly-justify-the-same">C. Drop other features if required using relevant functional knowledge. Clearly justify the same</h2>
<div class="cell" data-execution_count="93">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_signal[df_signal.duplicated()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="93">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">577</th>
<th data-quarto-table-cell-role="th">582</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">584</th>
<th data-quarto-table-cell-role="th">585</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">588</th>
<th data-quarto-table-cell-role="th">589</th>
<th data-quarto-table-cell-role="th">Pass/Fail</th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<p>0 rows × 444 columns</p>
</div>
</div>
</div>
<ul>
<li>Hence, there are no duplicate rows</li>
</ul>
<div class="cell" data-execution_count="94">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df_signal.columns[<span class="dv">1</span>:]:</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">round</span>(df_signal[col].std(),<span class="dv">2</span>)<span class="op">==</span><span class="dv">0</span>:</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>        df_signal.drop(col, axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">pass</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="95">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_signal.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="95">
<pre><code>(1567, 410)</code></pre>
</div>
</div>
</section>
<section id="d.-check-for-multi-collinearity-in-the-data-and-take-necessary-action" class="level2">
<h2 class="anchored" data-anchor-id="d.-check-for-multi-collinearity-in-the-data-and-take-necessary-action">D. Check for multi-collinearity in the data and take necessary action</h2>
<div class="cell" data-execution_count="96">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>threshold <span class="op">=</span> <span class="fl">0.85</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>corr_matrix <span class="op">=</span> df_signal.corr().<span class="bu">abs</span>()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>upper <span class="op">=</span> corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k<span class="op">=</span><span class="dv">1</span>).astype(<span class="bu">bool</span>))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>high_correlation <span class="op">=</span> [column <span class="cf">for</span> column <span class="kw">in</span> upper.columns <span class="cf">if</span> <span class="bu">any</span>(upper[column] <span class="op">&gt;</span> threshold)]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>df_signal.drop(high_correlation, axis<span class="op">=</span><span class="dv">1</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="97">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_signal.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="97">
<pre><code>(1567, 221)</code></pre>
</div>
</div>
</section>
</section>
<section id="q3.-data-analysis-visualisation" class="level1">
<h1>Q3. Data analysis &amp; visualisation</h1>
<section id="a.-perform-a-detailed-univariate-analysis-with-appropriate-detailed-comments-after-each-analysis" class="level2">
<h2 class="anchored" data-anchor-id="a.-perform-a-detailed-univariate-analysis-with-appropriate-detailed-comments-after-each-analysis">A. Perform a detailed univariate Analysis with appropriate detailed comments after each analysis</h2>
<div class="cell" data-execution_count="98">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_signal.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="98">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
<th data-quarto-table-cell-role="th">Pass/Fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2008-07-19 11:55:00</td>
<td>3030.93</td>
<td>2564.00</td>
<td>2187.7333</td>
<td>1411.1265</td>
<td>1.3602</td>
<td>97.6133</td>
<td>0.1242</td>
<td>1.5005</td>
<td>0.0162</td>
<td>...</td>
<td>0.14561</td>
<td>533.8500</td>
<td>2.1113</td>
<td>8.95</td>
<td>0.3157</td>
<td>0.0118</td>
<td>0.021458</td>
<td>0.016475</td>
<td>99.670066</td>
<td>-1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2008-07-19 12:32:00</td>
<td>3095.78</td>
<td>2465.14</td>
<td>2230.4222</td>
<td>1463.6606</td>
<td>0.8294</td>
<td>102.3433</td>
<td>0.1247</td>
<td>1.4966</td>
<td>-0.0005</td>
<td>...</td>
<td>0.14561</td>
<td>535.0164</td>
<td>2.4335</td>
<td>5.92</td>
<td>0.2653</td>
<td>0.0223</td>
<td>0.009600</td>
<td>0.020100</td>
<td>208.204500</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2008-07-19 13:17:00</td>
<td>2932.61</td>
<td>2559.94</td>
<td>2186.4111</td>
<td>1698.0172</td>
<td>1.5102</td>
<td>95.4878</td>
<td>0.1241</td>
<td>1.4436</td>
<td>0.0041</td>
<td>...</td>
<td>0.62190</td>
<td>535.0245</td>
<td>2.0293</td>
<td>11.21</td>
<td>0.1882</td>
<td>0.0157</td>
<td>0.058400</td>
<td>0.048400</td>
<td>82.860200</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2008-07-19 14:43:00</td>
<td>2988.72</td>
<td>2479.90</td>
<td>2199.0333</td>
<td>909.7926</td>
<td>1.3204</td>
<td>104.2367</td>
<td>0.1217</td>
<td>1.4882</td>
<td>-0.0124</td>
<td>...</td>
<td>0.16300</td>
<td>530.5682</td>
<td>2.0253</td>
<td>9.33</td>
<td>0.1738</td>
<td>0.0103</td>
<td>0.020200</td>
<td>0.014900</td>
<td>73.843200</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2008-07-19 15:22:00</td>
<td>3032.24</td>
<td>2502.87</td>
<td>2233.3667</td>
<td>1326.5200</td>
<td>1.5334</td>
<td>100.3967</td>
<td>0.1235</td>
<td>1.5031</td>
<td>-0.0031</td>
<td>...</td>
<td>0.14561</td>
<td>532.0155</td>
<td>2.0275</td>
<td>8.83</td>
<td>0.2224</td>
<td>0.4766</td>
<td>0.020200</td>
<td>0.014900</td>
<td>73.843200</td>
<td>-1</td>
</tr>
</tbody>
</table>

<p>5 rows × 221 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="99">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Univariate Boxplot for column 0</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_signal.boxplot(column<span class="op">=</span>[<span class="st">'0'</span>], return_type<span class="op">=</span><span class="st">'axes'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AxesSubplot(0.125,0.125;0.775x0.755)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-20-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The above boxplot for column 0 shows the median at around ~3000 value, and there are multiple values that lie outside the Q1 and Q3 range. The maximum value is near ~3350, while the minimum value is less than ~2750.</p>
<div class="cell" data-execution_count="100">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Univariate Scatterplot for column 1</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(df_signal.index,df_signal[<span class="st">'1'</span>])</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-21-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The above scatterplot for column 1 shows that there is no strong are where most of the datapoints are scattered. The distribution is failrly uniformly distributed from beginning to end.</p>
<div class="cell" data-execution_count="101">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Univariate Scatterplot for column 2</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span>df_signal.index,y<span class="op">=</span>df_signal[<span class="st">'2'</span>], hue<span class="op">=</span>df_signal[<span class="st">'Pass/Fail'</span>])</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-22-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The above scatterplot for column 2 shows that there is no strong are where most of the datapoints are scattered. The distribution is failrly uniformly distributed from beginning to end. However, most of the datapoints for “Fail” are scattered more to the right and left of the plot, whereas “Pass” is present throughout the distribution with more towards centre of the data</p>
<div class="cell" data-execution_count="102">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Univariate Histogram for column 3</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_signal[<span class="st">'3'</span>],bins<span class="op">=</span><span class="dv">20</span>,kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-23-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The above histogram shows that 1000-1500 has the most frequency distributed, with almost negligible datapoints less than 1000. The graph is mostlly uniform distributed with a little rightly skewed.</p>
</section>
<section id="b.-perform-bivariate-and-multivariate-analysis-with-appropriate-detailed-comments-after-each-analysis" class="level2">
<h2 class="anchored" data-anchor-id="b.-perform-bivariate-and-multivariate-analysis-with-appropriate-detailed-comments-after-each-analysis">B. Perform bivariate and multivariate analysis with appropriate detailed comments after each analysis</h2>
<div class="cell" data-execution_count="103">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot for Columns 4 Vs Pass/Fail</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>df_signal[<span class="st">'Pass/Fail'</span>],y<span class="op">=</span>df_signal[<span class="st">'4'</span>])</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The barplot for Column 4 Vs target feature, shows that there is more number of Pass, in comparison to Fail feature.</p>
<div class="cell" data-execution_count="104">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ViolinPlot for Columns 6 Vs Pass/Fail</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sns.violinplot(x<span class="op">=</span>df_signal[<span class="st">'Pass/Fail'</span>],y<span class="op">=</span>df_signal[<span class="st">'6'</span>],palette<span class="op">=</span><span class="st">'rainbow'</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-25-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The barplot for Column 6 Vs target feature, shows almost similar distribution. However, the edges of Pass is more scattered, whereas the Fail feature has most of the data within 90 to 110, with less scattering. There is negligible data for Fail feature after 120 value for Column 6</p>
<div class="cell" data-execution_count="105">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap for columns corr &gt; 0.98</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>corr<span class="op">=</span>df_signal.corr()</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">7</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr<span class="op">&gt;=</span><span class="fl">0.98</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations:</strong> The heatmap shows columns for which correlation coefficient is 0.98. Hence, the remaining columns are not a part of the heatmap. Regardless, we see that almost whole of the heatmap is close to black color, which shows that there is very minimal absolute correlation, and the most columns are independent of each other.</p>
</section>
</section>
<section id="q4" class="level1">
<h1>Q4</h1>
<section id="a.-segregate-predictors-vs-target-attributes" class="level2">
<h2 class="anchored" data-anchor-id="a.-segregate-predictors-vs-target-attributes">A. Segregate predictors vs target attributes</h2>
<div class="cell" data-execution_count="106">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_signal.drop([<span class="st">'Time'</span>,<span class="st">'Pass/Fail'</span>], axis<span class="op">=</span><span class="dv">1</span>) <span class="co"># Predictors</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_signal[[<span class="st">'Pass/Fail'</span>]] <span class="co"># Target Variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="107">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>X.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="107">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">564</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>3030.93</td>
<td>2564.00</td>
<td>2187.7333</td>
<td>1411.1265</td>
<td>1.3602</td>
<td>97.6133</td>
<td>0.1242</td>
<td>1.5005</td>
<td>0.0162</td>
<td>-0.0034</td>
<td>...</td>
<td>6.444985</td>
<td>0.14561</td>
<td>533.8500</td>
<td>2.1113</td>
<td>8.95</td>
<td>0.3157</td>
<td>0.0118</td>
<td>0.021458</td>
<td>0.016475</td>
<td>99.670066</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3095.78</td>
<td>2465.14</td>
<td>2230.4222</td>
<td>1463.6606</td>
<td>0.8294</td>
<td>102.3433</td>
<td>0.1247</td>
<td>1.4966</td>
<td>-0.0005</td>
<td>-0.0148</td>
<td>...</td>
<td>6.444985</td>
<td>0.14561</td>
<td>535.0164</td>
<td>2.4335</td>
<td>5.92</td>
<td>0.2653</td>
<td>0.0223</td>
<td>0.009600</td>
<td>0.020100</td>
<td>208.204500</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2932.61</td>
<td>2559.94</td>
<td>2186.4111</td>
<td>1698.0172</td>
<td>1.5102</td>
<td>95.4878</td>
<td>0.1241</td>
<td>1.4436</td>
<td>0.0041</td>
<td>0.0013</td>
<td>...</td>
<td>1.100000</td>
<td>0.62190</td>
<td>535.0245</td>
<td>2.0293</td>
<td>11.21</td>
<td>0.1882</td>
<td>0.0157</td>
<td>0.058400</td>
<td>0.048400</td>
<td>82.860200</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2988.72</td>
<td>2479.90</td>
<td>2199.0333</td>
<td>909.7926</td>
<td>1.3204</td>
<td>104.2367</td>
<td>0.1217</td>
<td>1.4882</td>
<td>-0.0124</td>
<td>-0.0033</td>
<td>...</td>
<td>7.320000</td>
<td>0.16300</td>
<td>530.5682</td>
<td>2.0253</td>
<td>9.33</td>
<td>0.1738</td>
<td>0.0103</td>
<td>0.020200</td>
<td>0.014900</td>
<td>73.843200</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3032.24</td>
<td>2502.87</td>
<td>2233.3667</td>
<td>1326.5200</td>
<td>1.5334</td>
<td>100.3967</td>
<td>0.1235</td>
<td>1.5031</td>
<td>-0.0031</td>
<td>-0.0072</td>
<td>...</td>
<td>6.444985</td>
<td>0.14561</td>
<td>532.0155</td>
<td>2.0275</td>
<td>8.83</td>
<td>0.2224</td>
<td>0.4766</td>
<td>0.020200</td>
<td>0.014900</td>
<td>73.843200</td>
</tr>
</tbody>
</table>

<p>5 rows × 219 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="108">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>y.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="108">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pass/Fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="b.-check-for-target-balancing-and-fix-it-if-found-imbalanced" class="level2">
<h2 class="anchored" data-anchor-id="b.-check-for-target-balancing-and-fix-it-if-found-imbalanced">B. Check for target balancing and fix it if found imbalanced</h2>
<div class="cell" data-execution_count="109">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y.value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pass/Fail
-1           1463
 1            104
dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="110">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>oversample<span class="op">=</span>SMOTE()</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>X,Y<span class="op">=</span>oversample.fit_resample(X,y)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>Y.value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="110">
<pre><code>Pass/Fail
-1           1463
 1           1463
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="c.-perform-train-test-split-and-standardise-the-data-or-vice-versa-if-required" class="level2">
<h2 class="anchored" data-anchor-id="c.-perform-train-test-split-and-standardise-the-data-or-vice-versa-if-required">C. Perform train-test split and standardise the data or vice versa if required</h2>
<div class="cell" data-execution_count="111">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> zscore</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>XScaled<span class="op">=</span>X.<span class="bu">apply</span>(zscore)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>XScaled.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="111">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">564</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.303750</td>
<td>0.947651</td>
<td>-0.465999</td>
<td>0.079211</td>
<td>-0.036271</td>
<td>-0.675140</td>
<td>0.327026</td>
<td>0.524000</td>
<td>1.344471</td>
<td>-0.420610</td>
<td>...</td>
<td>-0.032018</td>
<td>-0.099245</td>
<td>0.199153</td>
<td>0.029293</td>
<td>-0.207883</td>
<td>-0.049883</td>
<td>-0.281063</td>
<td>-0.022273</td>
<td>-0.067951</td>
<td>-0.004427</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.192926</td>
<td>-0.442705</td>
<td>1.105731</td>
<td>0.220341</td>
<td>-0.049195</td>
<td>0.234284</td>
<td>0.402482</td>
<td>0.462152</td>
<td>0.090688</td>
<td>-1.734014</td>
<td>...</td>
<td>-0.032018</td>
<td>-0.099245</td>
<td>0.254124</td>
<td>1.154726</td>
<td>-0.250978</td>
<td>-0.307125</td>
<td>0.520744</td>
<td>-1.083597</td>
<td>0.375512</td>
<td>1.309319</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.044342</td>
<td>0.890552</td>
<td>-0.514680</td>
<td>0.849929</td>
<td>-0.032619</td>
<td>-1.083804</td>
<td>0.311935</td>
<td>-0.378341</td>
<td>0.436042</td>
<td>0.120881</td>
<td>...</td>
<td>-2.463225</td>
<td>6.082150</td>
<td>0.254506</td>
<td>-0.257130</td>
<td>-0.175739</td>
<td>-0.700643</td>
<td>0.016751</td>
<td>3.283982</td>
<td>3.837489</td>
<td>-0.207900</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.275003</td>
<td>-0.235122</td>
<td>-0.049953</td>
<td>-1.267598</td>
<td>-0.037240</td>
<td>0.598323</td>
<td>-0.050251</td>
<td>0.328942</td>
<td>-0.802726</td>
<td>-0.409089</td>
<td>...</td>
<td>0.365990</td>
<td>0.126453</td>
<td>0.044484</td>
<td>-0.271102</td>
<td>-0.202478</td>
<td>-0.774140</td>
<td>-0.395606</td>
<td>-0.134901</td>
<td>-0.260611</td>
<td>-0.317046</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.321712</td>
<td>0.087926</td>
<td>1.214142</td>
<td>-0.148080</td>
<td>-0.032054</td>
<td>-0.139983</td>
<td>0.221389</td>
<td>0.565232</td>
<td>-0.104512</td>
<td>-0.858411</td>
<td>...</td>
<td>-0.032018</td>
<td>-0.099245</td>
<td>0.112694</td>
<td>-0.263417</td>
<td>-0.209589</td>
<td>-0.526086</td>
<td>35.212251</td>
<td>-0.134901</td>
<td>-0.260611</td>
<td>-0.317046</td>
</tr>
</tbody>
</table>

<p>5 rows × 219 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="112">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(XScaled, Y, train_size <span class="op">=</span> <span class="fl">.80</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="d.-check-if-the-train-and-test-data-have-similar-statistical-characteristics-when-compared-with-original-data" class="level2">
<h2 class="anchored" data-anchor-id="d.-check-if-the-train-and-test-data-have-similar-statistical-characteristics-when-compared-with-original-data">D. Check if the train and test data have similar statistical characteristics when compared with original data</h2>
<div class="cell" data-execution_count="113">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5 point summary of the original data</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>X.describe().loc[[<span class="st">'min'</span>,<span class="st">'25%'</span>,<span class="st">'50%'</span>,<span class="st">'75%'</span>,<span class="st">'max'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="113">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">564</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>2743.240000</td>
<td>2158.750000</td>
<td>2060.660000</td>
<td>0.000000</td>
<td>0.681500</td>
<td>82.131100</td>
<td>0.000000</td>
<td>1.191000</td>
<td>-0.053400</td>
<td>-0.034900</td>
<td>...</td>
<td>0.970000</td>
<td>0.022400</td>
<td>317.196400</td>
<td>0.980200</td>
<td>3.540000</td>
<td>0.066700</td>
<td>0.0060</td>
<td>-0.016900</td>
<td>0.003200</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>2960.587175</td>
<td>2457.536272</td>
<td>2182.622200</td>
<td>1111.476400</td>
<td>1.075174</td>
<td>98.712200</td>
<td>0.121195</td>
<td>1.427517</td>
<td>-0.009891</td>
<td>-0.004894</td>
<td>...</td>
<td>4.980000</td>
<td>0.095631</td>
<td>530.997453</td>
<td>1.994300</td>
<td>7.710000</td>
<td>0.234314</td>
<td>0.0118</td>
<td>0.014411</td>
<td>0.011300</td>
<td>48.705907</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>2998.035000</td>
<td>2499.770000</td>
<td>2198.698308</td>
<td>1302.660700</td>
<td>1.309595</td>
<td>101.362425</td>
<td>0.122277</td>
<td>1.466131</td>
<td>-0.001900</td>
<td>0.000804</td>
<td>...</td>
<td>6.390000</td>
<td>0.145610</td>
<td>532.490194</td>
<td>2.144062</td>
<td>8.865433</td>
<td>0.291833</td>
<td>0.0141</td>
<td>0.020800</td>
<td>0.015773</td>
<td>75.744454</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>3049.178807</td>
<td>2534.478138</td>
<td>2215.790906</td>
<td>1578.102105</td>
<td>1.489000</td>
<td>103.884833</td>
<td>0.123556</td>
<td>1.510726</td>
<td>0.005927</td>
<td>0.005700</td>
<td>...</td>
<td>7.470579</td>
<td>0.178265</td>
<td>534.273205</td>
<td>2.302658</td>
<td>10.095075</td>
<td>0.360600</td>
<td>0.0168</td>
<td>0.027669</td>
<td>0.021000</td>
<td>121.653250</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>3356.350000</td>
<td>2846.440000</td>
<td>2315.266700</td>
<td>3715.041700</td>
<td>1114.536600</td>
<td>129.252200</td>
<td>0.128600</td>
<td>1.656400</td>
<td>0.074900</td>
<td>0.053000</td>
<td>...</td>
<td>32.580000</td>
<td>0.689200</td>
<td>589.508200</td>
<td>2.739500</td>
<td>454.560000</td>
<td>2.196700</td>
<td>0.4766</td>
<td>0.102800</td>
<td>0.079900</td>
<td>737.304800</td>
</tr>
</tbody>
</table>

<p>5 rows × 219 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="114">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of the Training data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>X_train.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="114">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">564</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>...</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
<td>2340.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>0.000988</td>
<td>0.004691</td>
<td>-0.010001</td>
<td>-0.010020</td>
<td>0.009438</td>
<td>-0.000620</td>
<td>-0.012190</td>
<td>0.018574</td>
<td>-0.012164</td>
<td>-0.012249</td>
<td>...</td>
<td>-0.001099</td>
<td>0.018057</td>
<td>-0.010527</td>
<td>0.007940</td>
<td>0.001426</td>
<td>-0.001827</td>
<td>0.007871</td>
<td>0.003421</td>
<td>0.006602</td>
<td>-0.002435</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>1.011123</td>
<td>0.985903</td>
<td>0.982061</td>
<td>0.981078</td>
<td>1.118255</td>
<td>0.994716</td>
<td>1.109311</td>
<td>0.984026</td>
<td>0.991069</td>
<td>1.009566</td>
<td>...</td>
<td>0.971454</td>
<td>1.022435</td>
<td>1.055517</td>
<td>0.994409</td>
<td>0.998569</td>
<td>0.965238</td>
<td>1.102499</td>
<td>1.000731</td>
<td>1.001266</td>
<td>0.997663</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>-3.640845</td>
<td>-4.751740</td>
<td>-5.144613</td>
<td>-3.711711</td>
<td>-0.052797</td>
<td>-3.651859</td>
<td>-18.416120</td>
<td>-4.384166</td>
<td>-3.880876</td>
<td>-4.049752</td>
<td>...</td>
<td>-2.463225</td>
<td>-1.698283</td>
<td>-10.011539</td>
<td>-3.921600</td>
<td>-0.266339</td>
<td>-1.320778</td>
<td>-0.723965</td>
<td>-3.455335</td>
<td>-1.691888</td>
<td>-1.210874</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>-0.665911</td>
<td>-0.532087</td>
<td>-0.638936</td>
<td>-0.725855</td>
<td>-0.043099</td>
<td>-0.469625</td>
<td>-0.125707</td>
<td>-0.618275</td>
<td>-0.622542</td>
<td>-0.605475</td>
<td>...</td>
<td>-0.698377</td>
<td>-0.748852</td>
<td>0.064877</td>
<td>-0.379384</td>
<td>-0.225948</td>
<td>-0.472691</td>
<td>-0.281063</td>
<td>-0.650911</td>
<td>-0.688771</td>
<td>-0.617664</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>-0.144994</td>
<td>0.051289</td>
<td>-0.062663</td>
<td>-0.217475</td>
<td>-0.037328</td>
<td>0.043734</td>
<td>0.036133</td>
<td>0.008097</td>
<td>-0.025259</td>
<td>0.053403</td>
<td>...</td>
<td>-0.057028</td>
<td>-0.099245</td>
<td>0.134380</td>
<td>0.144470</td>
<td>-0.209576</td>
<td>-0.166899</td>
<td>-0.105717</td>
<td>-0.058268</td>
<td>-0.140662</td>
<td>-0.295600</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>0.544012</td>
<td>0.532126</td>
<td>0.556730</td>
<td>0.512652</td>
<td>-0.032831</td>
<td>0.519003</td>
<td>0.226139</td>
<td>0.695786</td>
<td>0.548657</td>
<td>0.608595</td>
<td>...</td>
<td>0.440256</td>
<td>0.350976</td>
<td>0.220321</td>
<td>0.707853</td>
<td>-0.192522</td>
<td>0.180441</td>
<td>0.106530</td>
<td>0.536345</td>
<td>0.485610</td>
<td>0.278644</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>4.765671</td>
<td>4.919856</td>
<td>4.229555</td>
<td>6.268567</td>
<td>27.068461</td>
<td>5.407983</td>
<td>0.991035</td>
<td>2.956674</td>
<td>5.751482</td>
<td>6.077283</td>
<td>...</td>
<td>5.956190</td>
<td>6.955583</td>
<td>2.822274</td>
<td>2.223574</td>
<td>6.130029</td>
<td>9.550733</td>
<td>35.212251</td>
<td>7.257763</td>
<td>7.690926</td>
<td>7.713766</td>
</tr>
</tbody>
</table>

<p>8 rows × 219 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="115">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5 point summary of the Training data</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>X_test.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="115">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">564</th>
<th data-quarto-table-cell-role="th">565</th>
<th data-quarto-table-cell-role="th">570</th>
<th data-quarto-table-cell-role="th">571</th>
<th data-quarto-table-cell-role="th">572</th>
<th data-quarto-table-cell-role="th">573</th>
<th data-quarto-table-cell-role="th">583</th>
<th data-quarto-table-cell-role="th">586</th>
<th data-quarto-table-cell-role="th">587</th>
<th data-quarto-table-cell-role="th">589</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>...</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
<td>586.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>-0.003944</td>
<td>-0.018733</td>
<td>0.039936</td>
<td>0.040013</td>
<td>-0.037687</td>
<td>0.002474</td>
<td>0.048678</td>
<td>-0.074167</td>
<td>0.048571</td>
<td>0.048910</td>
<td>...</td>
<td>0.004387</td>
<td>-0.072107</td>
<td>0.042036</td>
<td>-0.031707</td>
<td>-0.005694</td>
<td>0.007296</td>
<td>-0.031429</td>
<td>-0.013661</td>
<td>-0.026361</td>
<td>0.009724</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>0.956013</td>
<td>1.055894</td>
<td>1.069385</td>
<td>1.072984</td>
<td>0.009547</td>
<td>1.022521</td>
<td>0.280293</td>
<td>1.059835</td>
<td>1.035163</td>
<td>0.961022</td>
<td>...</td>
<td>1.108337</td>
<td>0.903045</td>
<td>0.738199</td>
<td>1.023106</td>
<td>1.007379</td>
<td>1.129822</td>
<td>0.374877</td>
<td>0.998667</td>
<td>0.996201</td>
<td>1.010922</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>-2.632107</td>
<td>-4.693796</td>
<td>-5.144613</td>
<td>-1.801575</td>
<td>-0.052797</td>
<td>-3.651859</td>
<td>-0.910444</td>
<td>-4.233512</td>
<td>-2.822293</td>
<td>-3.358487</td>
<td>...</td>
<td>-2.522356</td>
<td>-1.695687</td>
<td>-9.315659</td>
<td>-3.844056</td>
<td>-0.284829</td>
<td>-1.320778</td>
<td>-0.662875</td>
<td>-2.363441</td>
<td>-1.533593</td>
<td>-1.210874</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>-0.649964</td>
<td>-0.624182</td>
<td>-0.703066</td>
<td>-0.723181</td>
<td>-0.043613</td>
<td>-0.400718</td>
<td>-0.132529</td>
<td>-0.741498</td>
<td>-0.560103</td>
<td>-0.535821</td>
<td>...</td>
<td>-0.698377</td>
<td>-0.744142</td>
<td>0.063946</td>
<td>-0.413615</td>
<td>-0.224666</td>
<td>-0.454783</td>
<td>-0.281063</td>
<td>-0.658208</td>
<td>-0.746878</td>
<td>-0.641112</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>-0.167369</td>
<td>0.012895</td>
<td>-0.061407</td>
<td>-0.197446</td>
<td>-0.037922</td>
<td>0.074491</td>
<td>0.040296</td>
<td>-0.095159</td>
<td>0.025019</td>
<td>0.107648</td>
<td>...</td>
<td>-0.053946</td>
<td>-0.112377</td>
<td>0.136428</td>
<td>0.137575</td>
<td>-0.207477</td>
<td>-0.176889</td>
<td>-0.091871</td>
<td>-0.131625</td>
<td>-0.219084</td>
<td>-0.277787</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>0.579312</td>
<td>0.534349</td>
<td>0.613668</td>
<td>0.552470</td>
<td>-0.034167</td>
<td>0.563503</td>
<td>0.236480</td>
<td>0.572741</td>
<td>0.690784</td>
<td>0.685415</td>
<td>...</td>
<td>0.395522</td>
<td>0.171552</td>
<td>0.214126</td>
<td>0.650841</td>
<td>-0.189393</td>
<td>0.177245</td>
<td>0.092094</td>
<td>0.509495</td>
<td>0.473232</td>
<td>0.194555</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>4.540532</td>
<td>4.821690</td>
<td>4.229555</td>
<td>5.772096</td>
<td>0.032803</td>
<td>5.407983</td>
<td>0.840124</td>
<td>2.996320</td>
<td>3.761946</td>
<td>3.243096</td>
<td>...</td>
<td>11.855693</td>
<td>5.571719</td>
<td>0.494737</td>
<td>2.223574</td>
<td>6.005436</td>
<td>9.550733</td>
<td>2.250459</td>
<td>7.257763</td>
<td>6.492079</td>
<td>5.799779</td>
</tr>
</tbody>
</table>

<p>8 rows × 219 columns</p>
</div>
</div>
</div>
<section id="observations-1" class="level3">
<h3 class="anchored" data-anchor-id="observations-1">Observations</h3>
<ol type="1">
<li>The training and testing data are scaled. Whereas the original data isn’t scaled. Hence, even on splitting the training and testing data, the mean of train and test is close to 0, whereas Standard deviation is close to 1 for both of these. However, for the original data, the mean and Standard Deviation is way scattered for all columns.</li>
<li>The datapoints for all columns in the training and testing data have for most columns, min values near -3, and max values near +5/6. Whereas for most columns in the original dataset, the min and max values are in 1000s.</li>
<li>The original dataset has 591 predictor columns, whereas the training and testing data has 219 predictor columns and 1 target column</li>
</ol>
</section>
</section>
</section>
<section id="q5.-model-training-testing-and-tuning" class="level1">
<h1>Q5. Model training, testing and tuning</h1>
<section id="a.-use-any-supervised-learning-technique-to-train-a-model" class="level2">
<h2 class="anchored" data-anchor-id="a.-use-any-supervised-learning-technique-to-train-a-model">A. Use any Supervised Learning technique to train a model</h2>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> KNeighborsClassifier</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>NNH <span class="op">=</span> KNeighborsClassifier(weights <span class="op">=</span> <span class="st">'distance'</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>NNH.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/root/mambaforge/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="36">
<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>KNeighborsClassifier(weights='distance')</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">KNeighborsClassifier</label><div class="sk-toggleable__content"><pre>KNeighborsClassifier(weights='distance')</pre></div></div></div></div></div>
</div>
</div>
</section>
<section id="b.-use-cross-validation-techniques" class="level2">
<h2 class="anchored" data-anchor-id="b.-use-cross-validation-techniques">B. Use cross validation techniques</h2>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> StratifiedKFold, cross_val_score, GridSearchCV, RandomizedSearchCV</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="using-gridsearch-k-fold-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="using-gridsearch-k-fold-cross-validation">Using GridSearch &amp; K fold cross validation</h3>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier()</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>k_range <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">31</span>))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> <span class="bu">dict</span>(n_neighbors<span class="op">=</span>k_range)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># defining parameter range</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> GridSearchCV(knn, param_grid, cv<span class="op">=</span><span class="dv">10</span>, scoring<span class="op">=</span><span class="st">'accuracy'</span>, return_train_score<span class="op">=</span><span class="va">False</span>,verbose<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model for grid search</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>grid_search<span class="op">=</span>grid.fit(X_train, y_train.values.ravel())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 10 folds for each of 30 candidates, totalling 300 fits</code></pre>
</div>
</div>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_search.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'n_neighbors': 2}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> grid_search.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy))</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier(<span class="op">**</span>grid_search.best_params_)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>knn.fit(X_train, y_train.values.ravel())</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>y_test_predicted<span class="op">=</span>knn.predict(X_test) </span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>test_accuracy<span class="op">=</span>accuracy_score(y_test,y_test_predicted)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 75.17%
Accuracy for our testing dataset is : 77.30%</code></pre>
</div>
</div>
</section>
<section id="using-randomsearchcv" class="level3">
<h3 class="anchored" data-anchor-id="using-randomsearchcv">Using RandomSearchCV</h3>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set search parameters</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>n_neighbors <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">51</span>))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>random_grid <span class="op">=</span> {</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_neighbors'</span>: n_neighbors</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># run search</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier() </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>knn_random_search <span class="op">=</span> RandomizedSearchCV(estimator <span class="op">=</span> knn, random_state <span class="op">=</span> <span class="dv">42</span>,param_distributions <span class="op">=</span> random_grid,n_iter <span class="op">=</span> <span class="dv">50</span>, cv<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>knn_random_search.fit(X_train,y_train.values.ravel())</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(knn_random_search.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'n_neighbors': 2}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> knn_random_search.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy))</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier(<span class="op">**</span>knn_random_search.best_params_)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>knn.fit(X_train, y_train.values.ravel())</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>y_test_predicted<span class="op">=</span>knn.predict(X_test) </span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>test_accuracy<span class="op">=</span>accuracy_score(y_test,y_test_predicted)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 73.63%
Accuracy for our testing dataset is : 77.30%</code></pre>
</div>
</div>
</section>
</section>
<section id="c.-apply-hyper-parameter-tuning-techniques-to-get-the-best-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="c.-apply-hyper-parameter-tuning-techniques-to-get-the-best-accuracy">C. Apply hyper-parameter tuning techniques to get the best accuracy</h2>
<div class="cell" data-tags="[]" data-execution_count="43">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>n_neighbors <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">21</span>))</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> [<span class="st">'uniform'</span>,<span class="st">'distance'</span>]</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ,'chebyshev','seuclidean','minkowski'</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>metric <span class="op">=</span> [<span class="st">'euclidean'</span>,<span class="st">'manhattan'</span>,<span class="st">'chebyshev'</span>,<span class="st">'minkowski'</span>]</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_neighbors'</span>: n_neighbors,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'weights'</span>: weights,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'metric'</span>: metric,</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="co"># defining parameter range</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> GridSearchCV(knn, param_grid, cv<span class="op">=</span><span class="dv">2</span>, scoring<span class="op">=</span><span class="st">'accuracy'</span>, return_train_score<span class="op">=</span><span class="va">False</span>,verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model for grid search</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>grid_search<span class="op">=</span>grid.fit(X_train, y_train.values.ravel())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_search.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'uniform'}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> grid_search.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy))</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier(<span class="op">**</span>grid_search.best_params_)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>knn.fit(X_train, y_train.values.ravel())</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted<span class="op">=</span>knn.predict(X_test) </span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>test_accuracy<span class="op">=</span>accuracy_score(y_test,y_test_predicted)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 84.91%
Accuracy for our testing dataset is : 89.93%</code></pre>
</div>
</div>
<ul>
<li>Hence, accuracy for the testing data improved from 77.13% to 89.42%</li>
</ul>
</section>
<section id="d.-use-any-other-techniquemethod-which-can-enhance-the-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="d.-use-any-other-techniquemethod-which-can-enhance-the-model-performance">D. Use any other technique/method which can enhance the model performance</h2>
<section id="using-pca" class="level4">
<h4 class="anchored" data-anchor-id="using-pca">Using PCA</h4>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-tags="[]" data-execution_count="47">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># independant variables</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_signal.drop([<span class="st">'Time'</span>,<span class="st">'Pass/Fail'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the dependent variable</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_signal[[<span class="st">'Pass/Fail'</span>]]</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Scaling the data</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> zscore</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>XScaled<span class="op">=</span>X.<span class="bu">apply</span>(zscore)</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>XScaled.head()</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>X_train_Scaled, X_test_Scaled, y_train, y_test <span class="op">=</span> train_test_split(XScaled, y, train_size <span class="op">=</span> <span class="fl">.80</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA()</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>pca.fit(X_train_Scaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<style>#sk-container-id-2 {color: black;background-color: white;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>PCA()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox" checked=""><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">PCA</label><div class="sk-toggleable__content"><pre>PCA()</pre></div></div></div></div></div>
</div>
</div>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>X_train_Scaled.shape, X_test_Scaled.shape, y_train.shape, y_test.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<pre><code>((1253, 219), (314, 219), (1253, 1), (314, 1))</code></pre>
</div>
</div>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>plt.step(<span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>,<span class="dv">220</span>)),np.cumsum(pca.explained_variance_ratio_), where<span class="op">=</span><span class="st">'mid'</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cum of variation explained'</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'eigen Value'</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Kashish_Project_FMT_files/figure-html/cell-50-output-1.png" class="img-fluid"></p>
</div>
</div>
<ul>
<li>Hence, 150 seems a reasonable number as it provides details for more than 90% of the data.</li>
</ul>
<div class="cell" data-tags="[]" data-execution_count="50">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>pca_150 <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">150</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>pca_150.fit(X_train_Scaled)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pca_150.components_)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pca_150.explained_variance_ratio_)</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>X_train_pca_150 <span class="op">=</span> pca_150.transform(X_train_Scaled)</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>X_test_pca_150 <span class="op">=</span> pca_150.transform(X_test_Scaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[ 0.03938479 -0.00962393 -0.00831935 ...  0.04095677 -0.02262124
  -0.02406935]
 [-0.03202975  0.00375315 -0.0026834  ... -0.03325954  0.01490864
   0.04304356]
 [-0.0142449   0.01896111  0.01300556 ...  0.02364228 -0.0181542
   0.00191123]
 ...
 [-0.04338855 -0.03769048 -0.12696734 ...  0.00747138 -0.01306392
   0.02485897]
 [-0.11371288 -0.05893558  0.03160337 ...  0.03596548  0.01682052
   0.11448289]
 [ 0.00503752  0.0012111  -0.06212179 ... -0.02756968 -0.00319345
   0.04359276]]
[0.0370038  0.03450443 0.02603429 0.02377904 0.02068867 0.01882757
 0.01749734 0.01705101 0.01633056 0.01515553 0.01477653 0.0138589
 0.01349541 0.01308603 0.0123518  0.01202757 0.01153699 0.01118827
 0.01095144 0.01064651 0.0104699  0.01014938 0.01002054 0.00986464
 0.00963785 0.00936522 0.00920846 0.0089866  0.00892498 0.0087549
 0.00863545 0.00837104 0.00829717 0.00821941 0.00806974 0.00797659
 0.00785637 0.00782897 0.00759071 0.00756261 0.00733198 0.00723833
 0.00703627 0.00699853 0.00690608 0.0068113  0.00663966 0.00656817
 0.00640558 0.00637213 0.0062181  0.00616637 0.00602233 0.0059265
 0.0058663  0.00580148 0.0057187  0.0056413  0.00558692 0.0054691
 0.00546114 0.00534963 0.00524832 0.00522674 0.00510006 0.00503965
 0.00499511 0.00497757 0.00486902 0.00483147 0.00481512 0.00478103
 0.00474463 0.00458248 0.00453756 0.00449839 0.00444766 0.00439482
 0.00433793 0.00426739 0.00426244 0.00416934 0.00415997 0.00414733
 0.00407816 0.0040365  0.00397064 0.00395675 0.00386878 0.00383371
 0.00379375 0.00377355 0.00370793 0.00366804 0.00360056 0.00359344
 0.00356027 0.00352344 0.00346675 0.0034159  0.00335451 0.00329097
 0.00328503 0.00323567 0.00319627 0.0031652  0.00312032 0.00307902
 0.00306405 0.00298322 0.00298051 0.00291885 0.00285646 0.00284202
 0.00281463 0.0027693  0.00274943 0.00269303 0.00264399 0.00256934
 0.00254754 0.00252876 0.00250861 0.00244676 0.00242878 0.00238322
 0.00235651 0.00231763 0.00227693 0.00223354 0.00220577 0.00217134
 0.00213081 0.00211738 0.00208823 0.00206284 0.00205128 0.00201749
 0.00195435 0.00193237 0.00190086 0.00183959 0.00181241 0.0017445
 0.00172531 0.00169588 0.00167287 0.00165556 0.00160906 0.00157944]</code></pre>
</div>
</div>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>n_neighbors <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">21</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> [<span class="st">'uniform'</span>,<span class="st">'distance'</span>]</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ,'chebyshev','seuclidean','minkowski'</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>metric <span class="op">=</span> [<span class="st">'euclidean'</span>,<span class="st">'manhattan'</span>,<span class="st">'chebyshev'</span>,<span class="st">'minkowski'</span>]</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_neighbors'</span>: n_neighbors,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'weights'</span>: weights,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'metric'</span>: metric,</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="co"># defining parameter range</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>grid_knn <span class="op">=</span> GridSearchCV(knn, param_grid, cv<span class="op">=</span><span class="dv">2</span>, scoring<span class="op">=</span><span class="st">'accuracy'</span>, return_train_score<span class="op">=</span><span class="va">False</span>,verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model for grid search</span></span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a>grid_search_knn<span class="op">=</span>grid_knn.fit(X_train_pca_150, y_train.values.ravel())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>accuracy_knn_train <span class="op">=</span> grid_search_knn.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_knn_train))</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>knn <span class="op">=</span> KNeighborsClassifier(<span class="op">**</span>grid_search_knn.best_params_)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>knn.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_knn<span class="op">=</span>knn.predict(X_test_pca_150) </span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_knn<span class="op">=</span>accuracy_score(y_test,y_test_predicted_knn)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_knn) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 92.82%
Accuracy for our testing dataset is : 95.54%</code></pre>
</div>
</div>
<ul>
<li>Hence, by performing (1) Scaling, (2) Dimensionality Reduction using PCA, (3) GridSearch K- Cross Validation, we were able to bring the accuracy score of our testing data to 95.54%</li>
</ul>
</section>
</section>
<section id="e.-display-and-explain-the-classification-report-in-detail" class="level2">
<h2 class="anchored" data-anchor-id="e.-display-and-explain-the-classification-report-in-detail">E. Display and explain the classification report in detail</h2>
<div class="cell" data-tags="[]" data-execution_count="53">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_test_predicted_knn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

          -1       0.96      1.00      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.96       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.96      0.94       314
</code></pre>
</div>
</div>
<section id="observations-2" class="level3">
<h3 class="anchored" data-anchor-id="observations-2">Observations</h3>
<ol type="1">
<li>The model provided precision score of 96% for Passed student and 100% recall. Hence, 98% of correct positive predictions relative to total positive predictions were correctly predicted. The F1-score, which is the harmonic mean of precision and recall is 98%, which indicates model did a good job.</li>
<li>Out of 314 test data points, 301 were passed data, and 13 were failed. Weighted average for precision recall and f1-score are 92%, 96% and 94%. This indicated the model has done a good job.</li>
<li>However, model wasn’t able to predict most fail values, hence, it didn’t do a good job to predict fail target feature value.</li>
</ol>
</section>
</section>
<section id="f.-apply-the-above-steps-for-all-possible-models-that-you-have-learnt-so-far" class="level2">
<h2 class="anchored" data-anchor-id="f.-apply-the-above-steps-for-all-possible-models-that-you-have-learnt-so-far">F. Apply the above steps for all possible models that you have learnt so far</h2>
<p>Note: 1. Since the dataset is based on classification, we will only create Supervised Machine Learning models 2. PCA and Scaling will be same for all the models, hence, this is already done ahead of other steps</p>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h3>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>logreg <span class="op">=</span> LogisticRegression()</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>logreg.fit(X_train_pca_150,y_train.values.ravel())</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> logreg.predict(X_test_pca_150)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn <span class="im">import</span> metrics</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>,metrics.accuracy_score(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.9171974522292994</code></pre>
</div>
</div>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># parameter grid</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>parameters <span class="op">=</span> {</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'penalty'</span> : [<span class="st">'l1'</span>,<span class="st">'l2'</span>], </span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'C'</span>       : np.logspace(<span class="op">-</span><span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">7</span>),</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'solver'</span>  : [<span class="st">'newton-cg'</span>, <span class="st">'lbfgs'</span>, <span class="st">'liblinear'</span>],</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>logreg <span class="op">=</span> LogisticRegression()</span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>grid_log <span class="op">=</span> GridSearchCV(logreg,                    <span class="co"># model</span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>                   param_grid <span class="op">=</span> parameters,   <span class="co"># hyperparameters</span></span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>                   scoring<span class="op">=</span><span class="st">'accuracy'</span>,        <span class="co"># metric for scoring</span></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a>                   cv<span class="op">=</span><span class="dv">3</span>)                     <span class="co"># number of folds</span></span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>grid_search_log <span class="op">=</span> grid_log.fit(X_train_pca_150,y_train.values.ravel())</span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_search_log.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'C': 0.001, 'penalty': 'l1', 'solver': 'liblinear'}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>accuracy_log <span class="op">=</span> grid_search_log.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_log))</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LogisticRegression(<span class="op">**</span>grid_search_log.best_params_)</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_log<span class="op">=</span>lr.predict(X_test_pca_150) </span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_log<span class="op">=</span>accuracy_score(y_test,y_test_predicted_log)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_log) )</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report Shown Below:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_test_predicted_log))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 92.74%
Accuracy for our testing dataset is : 95.86%

Classification Report Shown Below:

              precision    recall  f1-score   support

          -1       0.96      1.00      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.96       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.96      0.94       314
</code></pre>
</div>
</div>
</section>
<section id="random-forest-classifier" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-classifier">Random Forest Classifier</h3>
<div class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>rfc <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">50</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters and distributions to sample from</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>param_dist <span class="op">=</span> {<span class="st">"max_depth"</span>: [<span class="dv">3</span>, <span class="va">None</span>],</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">"max_features"</span>: sp_randint(<span class="dv">1</span>, <span class="dv">11</span>),</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>              <span class="st">"min_samples_split"</span>: sp_randint(<span class="dv">2</span>, <span class="dv">11</span>),</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>              <span class="st">"min_samples_leaf"</span>: sp_randint(<span class="dv">1</span>, <span class="dv">11</span>),</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>              <span class="st">"bootstrap"</span>: [<span class="va">True</span>, <span class="va">False</span>],</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>              <span class="st">"criterion"</span>: [<span class="st">"gini"</span>, <span class="st">"entropy"</span>]}</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a><span class="co"># run randomized search</span></span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>samples <span class="op">=</span> <span class="dv">10</span>  <span class="co"># number of random samples </span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>randomCV <span class="op">=</span> RandomizedSearchCV(rfc, param_distributions<span class="op">=</span>param_dist, n_iter<span class="op">=</span>samples, cv<span class="op">=</span><span class="dv">3</span>) <span class="co">#default cv = 3</span></span>
<span id="cb82-15"><a href="#cb82-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-16"><a href="#cb82-16" aria-hidden="true" tabindex="-1"></a>random_search_rfc <span class="op">=</span> randomCV.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb82-17"><a href="#cb82-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(random_search_rfc.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'bootstrap': False, 'criterion': 'gini', 'max_depth': None, 'max_features': 8, 'min_samples_leaf': 6, 'min_samples_split': 9}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>accuracy_rfc <span class="op">=</span> random_search_rfc.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_rfc))</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>rfc <span class="op">=</span> RandomForestClassifier(<span class="op">**</span>random_search_rfc.best_params_)</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>rfc.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_rfc<span class="op">=</span>rfc.predict(X_test_pca_150) </span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_rfc<span class="op">=</span>accuracy_score(y_test,y_test_predicted_rfc)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_rfc) )</span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report Shown Below:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_test_predicted_rfc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 92.74%
Accuracy for our testing dataset is : 95.86%

Classification Report Shown Below:

              precision    recall  f1-score   support

          -1       0.96      1.00      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.96       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.96      0.94       314
</code></pre>
</div>
</div>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> { </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_estimators'</span>: [<span class="dv">200</span>],</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_features'</span>: [<span class="st">'auto'</span>, <span class="st">'sqrt'</span>, <span class="st">'log2'</span>],</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span> : [<span class="dv">4</span>,<span class="dv">5</span>],</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'criterion'</span> :[<span class="st">'gini'</span>, <span class="st">'entropy'</span>]</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>rfc_grid_clf<span class="op">=</span>RandomForestClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>grid_CV_rfc <span class="op">=</span> GridSearchCV(estimator<span class="op">=</span>rfc_grid_clf, param_grid<span class="op">=</span>param_grid, cv<span class="op">=</span> <span class="dv">5</span>)</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>grid_CV_rfc_search <span class="op">=</span> grid_CV_rfc.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_CV_rfc_search.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'criterion': 'gini', 'max_depth': 4, 'max_features': 'auto', 'n_estimators': 200}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>accuracy_rfc_grid <span class="op">=</span> grid_CV_rfc_search.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_rfc_grid))</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>rfc_grid <span class="op">=</span> RandomForestClassifier(<span class="op">**</span>grid_CV_rfc_search.best_params_)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>rfc_grid.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_rfc_grid<span class="op">=</span>rfc_grid.predict(X_test_pca_150) </span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_rfc_grid<span class="op">=</span>accuracy_score(y_test,y_test_predicted_rfc_grid)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_rfc_grid) )</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report Shown Below:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_test_predicted_rfc_grid))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 92.74%
Accuracy for our testing dataset is : 95.86%

Classification Report Shown Below:

              precision    recall  f1-score   support

          -1       0.96      1.00      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.96       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.96      0.94       314
</code></pre>
</div>
</div>
</section>
<section id="support-vector-classifier" class="level3">
<h3 class="anchored" data-anchor-id="support-vector-classifier">Support Vector Classifier</h3>
<div class="cell" data-execution_count="59">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> SVC</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SVC()</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {<span class="st">'C'</span>: [<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">1000</span>], </span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>              <span class="st">'gamma'</span>: [<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>, <span class="fl">0.001</span>, <span class="fl">0.0001</span>],</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">'kernel'</span>: [<span class="st">'rbf'</span>]} </span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> GridSearchCV(model, param_grid, refit <span class="op">=</span> <span class="va">True</span>, verbose <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model for grid search</span></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>grid_search_svc <span class="op">=</span> grid.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_search_svc.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="60">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>accuracy_svc <span class="op">=</span> grid_search_svc.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_svc))</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>svc_model <span class="op">=</span> SVC(<span class="op">**</span>grid_search_svc.best_params_)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>svc_model.fit(X_train_pca_150, y_train.values.ravel())</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_svc<span class="op">=</span>svc_model.predict(X_test_pca_150) </span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_svc<span class="op">=</span>accuracy_score(y_test,y_test_predicted_svc)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_svc) )</span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-13"><a href="#cb92-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report Shown Below:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb92-14"><a href="#cb92-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_test_predicted_svc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 92.74%
Accuracy for our testing dataset is : 95.86%

Classification Report Shown Below:

              precision    recall  f1-score   support

          -1       0.96      1.00      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.96       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.96      0.94       314
</code></pre>
</div>
</div>
</section>
<section id="xgboost-classifier" class="level3">
<h3 class="anchored" data-anchor-id="xgboost-classifier">XGBoost Classifier</h3>
<div class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> xgboost <span class="im">import</span> XGBClassifier</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the search space</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> { </span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Percentage of columns to be randomly samples for each tree.</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"colsample_bytree"</span>: [ <span class="fl">0.3</span>, <span class="fl">0.5</span> , <span class="fl">0.8</span> ],</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># reg_alpha provides l1 regularization to the weight, higher values result in more conservative models</span></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"reg_alpha"</span>: [<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">5</span>],</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># reg_lambda provides l2 regularization to the weight, higher values result in more conservative models</span></span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"reg_lambda"</span>: [<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">5</span>]</span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up score</span></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a>scoring <span class="op">=</span> [<span class="st">'accuracy'</span>]</span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the k-fold cross-validation</span></span>
<span id="cb94-15"><a href="#cb94-15" aria-hidden="true" tabindex="-1"></a>kfold <span class="op">=</span> StratifiedKFold(n_splits<span class="op">=</span><span class="dv">3</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>XGB requires target class column to have values as 0,1,2. But our target class has value -1,1. Hence, using label encoder to train xgb.</li>
</ul>
<div class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>le <span class="op">=</span> LabelEncoder()</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>y_train_le <span class="op">=</span> le.fit_transform(y_train)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>y_test_le <span class="op">=</span> le.fit_transform(y_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define grid search</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>grid_search_xgb <span class="op">=</span> GridSearchCV(estimator<span class="op">=</span>XGBClassifier(),</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>                           param_grid<span class="op">=</span>param_grid,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>                           scoring<span class="op">=</span><span class="st">'roc_auc'</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>                           n_jobs<span class="op">=-</span><span class="dv">1</span>, refit<span class="op">=</span><span class="st">'recall'</span>,</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>                           cv<span class="op">=</span>kfold,</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>                           verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit grid search</span></span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>grid_result_xgb <span class="op">=</span> grid_search_xgb.fit(X_train_pca_150, y_train_le)</span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print grid search summary</span></span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid_result_xgb.best_params_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'colsample_bytree': 0.3, 'reg_alpha': 0, 'reg_lambda': 0.5}</code></pre>
</div>
</div>
<div class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>accuracy_xgb <span class="op">=</span> grid_result_xgb.best_score_ <span class="op">*</span><span class="dv">100</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our training dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(accuracy_xgb))</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>xgb_model <span class="op">=</span> XGBClassifier(<span class="op">**</span>grid_result_xgb.best_params_)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>xgb_model.fit(X_train_pca_150, y_train_le)</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>y_test_predicted_xgb<span class="op">=</span>xgb_model.predict(X_test_pca_150) </span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>test_accuracy_xgb<span class="op">=</span>accuracy_score(y_test_le,y_test_predicted_xgb)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy for our testing dataset is : </span><span class="sc">{:.2f}</span><span class="st">%"</span>.<span class="bu">format</span>(test_accuracy_xgb) )</span>
<span id="cb98-12"><a href="#cb98-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-13"><a href="#cb98-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Classification Report Shown Below:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb98-14"><a href="#cb98-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test_le, y_test_predicted_xgb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for our training dataset is : 68.75%
Accuracy for our testing dataset is : 95.22%

Classification Report Shown Below:

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       301
           1       0.00      0.00      0.00        13

    accuracy                           0.95       314
   macro avg       0.48      0.50      0.49       314
weighted avg       0.92      0.95      0.94       314
</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="q6.post-training-and-conclusion" class="level1">
<h1>Q6.Post Training and Conclusion</h1>
<section id="a.-display-and-compare-all-the-models-designed-with-their-train-and-test-accuracies" class="level2">
<h2 class="anchored" data-anchor-id="a.-display-and-compare-all-the-models-designed-with-their-train-and-test-accuracies">A. Display and compare all the models designed with their train and test accuracies</h2>
<div class="cell" data-execution_count="80">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>training_accuracies<span class="op">=</span>[accuracy_knn_train, accuracy_log, accuracy_rfc, accuracy_rfc_grid, accuracy_svc, accuracy_xgb]</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>testing_accuracies<span class="op">=</span>[test_accuracy_knn, test_accuracy_log, test_accuracy_rfc, test_accuracy_rfc_grid, test_accuracy_svc, test_accuracy_xgb]</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> {<span class="st">'Training Accuracy'</span> : training_accuracies, <span class="st">'Testing Accuracy'</span>: testing_accuracies}</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>index <span class="op">=</span>[<span class="st">'KNN '</span>, <span class="st">'Logistic Regression'</span>,<span class="st">'Random Forest RandomSearchCV'</span>, <span class="st">'Random Forest GridSearchCV'</span>, <span class="st">'Support Vector Classifier'</span>,<span class="st">'XGBoost'</span>]</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(data, index<span class="op">=</span>index)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="80">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Training Accuracy</th>
<th data-quarto-table-cell-role="th">Testing Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">KNN</td>
<td>92.817107</td>
<td>95.541401</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Logistic Regression</td>
<td>92.737485</td>
<td>95.859873</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Random Forest RandomSearchCV</td>
<td>92.737485</td>
<td>95.859873</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Random Forest GridSearchCV</td>
<td>92.737530</td>
<td>95.859873</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Support Vector Classifier</td>
<td>92.737530</td>
<td>95.859873</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">XGBoost</td>
<td>68.748535</td>
<td>95.222930</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="b.-select-the-final-best-trained-model-along-with-your-detailed-comments-for-selecting-this-model" class="level2">
<h2 class="anchored" data-anchor-id="b.-select-the-final-best-trained-model-along-with-your-detailed-comments-for-selecting-this-model">B. Select the final best trained model along with your detailed comments for selecting this model</h2>
<p>As observed from the above dataframe for training and testing accuracies, we find that all the models produced Fairly similarly good on the testing data with 95%+ testing accuracy. For training, XGBoost performed way worse with ~68%, however, the remaining models produced accuracies of ~92% on training data. The top 2 performing models on both training and test data are “Random Forest” &amp; “Support Vector Classifier”. The testing accuracy for both of these is same with the currrent optimisation, the training accuracy for SVC is slightly better than Random Forest. Regardless, on increasing depth of random forest and n_estimators, we can improve it’s accuracy, but due to heavy GPU computation, I couldn’t perform it on the current system. Hence, choosing Random Forest Model RandomisedSearch as the best trained model</p>
</section>
<section id="c.-pickle-the-selected-model-for-future-use" class="level2">
<h2 class="anchored" data-anchor-id="c.-pickle-the-selected-model-for-future-use">C. Pickle the selected model for future use</h2>
<div class="cell" data-execution_count="81">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>pickle.dump(rfc_grid, <span class="bu">open</span>(<span class="st">'model_random_forest.pkl'</span>, <span class="st">'wb'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="d.-write-your-conclusion-on-the-results" class="level2">
<h2 class="anchored" data-anchor-id="d.-write-your-conclusion-on-the-results">D. Write your conclusion on the results</h2>
<p>Detailed suggestions on the data points collected by the bank to do better Analysis in the future 1. The results of the model indicated that they did a good job in predicting passed status. However, none of them did a good job in predicted failed values. 2. There was high imbalance the data, and hence, upsampling was required to perform on the data 3. Suggestion would be to provide metadata on the features present in the dataset. The current columns were just a bunch of numerical numbers, which didn’t meant anything to the human eye. Hence, understanding what is the function of each column, will help the data scientist to logically infer which columns can be proved more useful than the other. 4. The data had multiple null values, and 450+ columns with no meaning. The data wasn’t well prepared to provide to a data scientist, and hence, required a lot of</p>
</section>
</section>
<section id="the-end" class="level1">
<h1>THE End</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>